### ISSUE TITLE
would your please share your vim theme?

### ISSUE THREAD

**Issue by xdada280** [jonhoo/configs#14]
i have tried many other themes, and they are either too much colorful or too harsh and i'm not able to customize one for myself. I've watched a lot of your videos and I feel like I'm getting used to yours :)

**Comment by jonhoo** [comment]
https://github.com/jonhoo/configs/blob/725647dc85667dd5dde88f824c52ff9755cb1a7e/editor/.config/nvim/init.vim#L72

:)

**Comment by xdada280** [comment]
thanks. i finally figure out is vim-rust-syntax-ext makes theme seems not right.
