### ISSUE TITLE
Could you share the font you used when programming?

### ISSUE THREAD

**Issue by Case3y** [jonhoo/configs#18]
Hi Jon!

I like the font in your video. But I didn't find it in the config files. Could you share the font which in the image?

<img width="960" alt="image" src="https://user-images.githubusercontent.com/71315026/201532200-f5926542-3366-41b8-b36f-2c63f7b94a79.png">

**Comment by WindSoilder** [comment]
Jump here to help: It's [noto sans mono](https://fonts.google.com/noto/specimen/Noto+Sans+Mono?noto.query=mono)

And it's defined in [alacritty.yml file](https://github.com/jonhoo/configs/blob/master/gui/.config/alacritty/alacritty.yml)

**Comment by Case3y** [comment]
> 

Thank you so much :)
