### ISSUE TITLE
jonhoo's custom gruvbox colorscheme

### ISSUE THREAD

**Issue by daniel-abramov** [jonhoo/configs#20]
I've once watched [a video on YouTube](https://youtu.be/O2Ds0U0pXo8?t=5134) and I quite enjoyed the color scheme and the font. By checking the configs I figured that the font is likely to be "Noto Mono" whereas the color scheme is "gruvbox".

After trying several variations of Noto Mono and Noto Sans Mono, I've gotten to the point where the font looks very similar, however, I was not quite able to get the same colors. I'm using Neovim and generally prefer using Lua-written plugins, but I nevertheless tried both `gruvbox.nvim` and `gruvbox-material`with different levels of contrast, but it never looks as good as in the video. It seems like the video uses a custom version of the gruvbox and I was wondering if there is a way to open-source this version so that other people who enjoy the same look and feel could use the color scheme :)

I find the "regular" gruvbox theme a bit too harsh.

Another difference might be caused by the fact that I'm using neovim treesitter instead of `rust.vim` for highlighting.

UPD. I've tried different flavors of gruvbox, for those who want to have colors as close as possible to those that were in the video linked above, I've got the best results with this one: https://github.com/eddyekofo94/gruvbox-flat.nvim

**Comment by jonhoo** [comment]
I don't use anything custom, it's just https://github.com/chriskempson/base16-vim/blob/master/colors/base16-gruvbox-dark-hard.vim if memory serves me right :)

**Comment by daniel-abramov** [comment]
Interesting. I've tried installing it, but the colors look different from those in the video recording of the live session 🙂

I wonder if this could be caused by the fact that I'm using treesitter instead of a rust.vim (most notably, the red color appears much more often and all the colors feel much more saturated). The closest I've gotten so far was to use the `gruvbox-flat` and its Lua alternatives.

**Comment by jonhoo** [comment]
Oh, yeah, almost certainly. Which syntax highlighter you use changes which colors are used for what, so even with the same theme, things may look different.
