### ISSUE TITLE
Add Firefox userChrome.css

### ISSUE THREAD

**Issue by timvisee** [jonhoo/configs#5]
I noticed you are using a custom Firefox `userChrome.css` in some of your coding videos, which puts your address bar at the bottom of the screen.

Would you mind sharing your configuration as part of this repository as well? That would be awesome.

**Comment by jonhoo** [comment]
It's [already there](https://github.com/jonhoo/configs/blob/master/gui/.mozilla/firefox/dev-edition-default/chrome/userChrome.css) :)
