### ISSUE TITLE
typing in a "s" results in a ">" prompt cropping up in the command-line window

### ISSUE THREAD

**Issue by zhangzhen** [jonhoo/configs#8]
MacOS Catalina
iterm2 Build 3.3.12
neovim v0.4.3

Your init.vim is used as my nvim configuration. In the normal mode, typing in a "s" results in a ">" prompt cropping up in the command-line window. There is no keybinding of s to that command in the config file. What is that command? How can I turn off the binding. Thank you in advance!

Zhen

**Comment by jonhoo** [comment]
That's be [`vim-sneak`](https://github.com/justinmk/vim-sneak), which lets you seek by two characters (as opposed to a single character with f/F/t/T). You can just comment out the `vim-sneak` plugin line and it should go away :)
